# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-03-19T22:56:14+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    result: str
    totalresults: str
    statuses_status__0__Pending_: str = Field(..., alias='statuses[status][0][Pending]')
    statuses_status__1__Active_: str = Field(..., alias='statuses[status][1][Active]')
    statuses_status__2__Fraud_: str = Field(..., alias='statuses[status][2][Fraud]')
    statuses_status__3__Cancelled_: str = Field(
        ..., alias='statuses[status][3][Cancelled]'
    )
    statuses_status__4__My_Custom_Status_: str = Field(
        ..., alias='statuses[status][4][My Custom Status]'
    )
