# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-03-19T22:46:46+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class LineitemItem(BaseModel):
    type: str
    relid: int
    producttype: str
    product: str
    domain: str
    billingcycle: str
    amount: str
    status: str


class Lineitems(BaseModel):
    lineitem: List[LineitemItem]


class OrderItem(BaseModel):
    id: int
    ordernum: int
    userid: int
    contactid: int
    date: str
    nameservers: str
    transfersecret: str
    renewals: str
    promocode: str
    promotype: str
    promovalue: str
    orderdata: str
    amount: str
    paymentmethod: str
    invoiceid: int
    status: str
    ipaddress: str
    fraudmodule: str
    fraudoutput: str
    notes: str
    paymentmethodname: str
    paymentstatus: str
    name: str
    currencyprefix: str
    currencysuffix: str
    frauddata: str
    lineitems: Lineitems


class Orders(BaseModel):
    order: List[OrderItem]


class Model(BaseModel):
    result: str
    totalresults: int
    startnumber: int
    numreturned: int
    orders: Orders
