# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-03-19T23:00:31+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class PromotionItem(BaseModel):
    id: int
    code: str
    type: str
    recurring: int
    value: int
    cycles: str
    appliesto: str
    requires: str
    requiresexisting: int
    startdate: str
    expirationdate: str
    maxuses: int
    uses: int
    lifetimepromo: int
    applyonce: int
    newsignups: int
    existingclient: int
    onceperclient: int
    recurfor: int
    upgrades: int
    upgradeconfig: str
    notes: str


class Promotions(BaseModel):
    promotion: List[PromotionItem]


class Model(BaseModel):
    result: str
    totalresults: int
    promotions: Promotions
